title: Trevor Nelson
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: Trevor Nelson's portfolio
color_scheme: light
accent_color: blue
header:
  title: TN
  has_nav: false
  # nav_links:
  #   - label: Home
  #     url: /
  #     style: link
  #   - label: About
  #     url: /about/
  #     style: link
footer:
  content: '&copy; Trevor Nelson. All rights reserved. Powered by Jekyll and Stackbit.'
  has_social: true
  social_links:
    - label: GitHub
      url: 'https://github.com/trevnels'
      style: icon
      icon_class: fa-github
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/in/trevor-nelson-a730411a0/'
      style: icon
      icon_class: fa-linkedin
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
