# The URL the site will be built for
base_url = "https://trevnels.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [{ name = "tags", feed = false, render = false }]

generate_feed = true

[markdown]
highlight_code = true
highlight_theme = "ayu-mirage"

render_emoji = true
external_links_target_blank = true
smart_punctuation = true

[extra]
# Put all your custom variables here
