name: Build and publish site

on:
  workflow_dispatch:
  push:
    branches:
      - v2
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: sudo snap install --edge zola
      - run: npm install
      - run: npm run build
      - name: Fix permissions
        run: |
          chmod -c -R +rX "public/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public/
